### ISSUE TITLE
Bracketed paste

### ISSUE THREAD

**Issue by ethercrow** [coreyoconnor/vty#50]
See http://cirw.in/blog/bracketed-paste

Would be nice if vty provided an event like `EvPaste Text`.

**Comment by jtdaugherty** [comment]
@coreyoconnor - I've implemented this in a branch on my fork.  This change would dovetail nicely with some of the changes made in my mouse event support branch, too.  And this change would also benefit from the same change I mentioned in https://github.com/coreyoconnor/vty/issues/38 about permitting the `XtermColor` driver to be used for `screen`-like terminals.

**Comment by jtdaugherty** [comment]
I should also note that if the mouse event support gets merged, I'd like to move this functionality to `Graphics.Vty.Input.Paste` and take advantage of the moved `KClass` type.  This change only lives in the `Classify` module because I didn't want to move `KClass` again and conflict with my other branch in the event that they both get merged.

**Comment by jtdaugherty** [comment]
This has been merged and will go out in the next release.

**Comment by jtdaugherty** [comment]
This is now released: http://hackage.haskell.org/package/vty-5.6
